[package]
name = "lupin_editor"
version = "0.1.0"
edition = "2021"

[dependencies]
lupin = { path = "../lupin" }

# GUI
winit = "0.29.7"
#wgpu  = "0.19.4"
#egui  = "0.27.2"
#egui-wgpu  = "0.27.2"
#egui-winit = "0.27.2"

# Serialization
tobj  = "4.0.2"
image = "0.25.0"